### PR TITLE
feat: change title font to Roboto Slab Thin

### PR DESCRIPTION
**Pull request by rickstaa**
This PR changes the title font to the Roboto Slab Thin font, which is now the new title font under the TUDelft house style. For more information, see https://www.tudelft.nl/huisstijl/bouwstenen/typografie.

### CODE REVIEW

**Comment by dzwaneveld** [comment]
Thanks for the heads-up!

Given that the new house style appears to favor Roboto Slab for titles in general and has removed Georgia as supplementary font, I would say we could expand this pull request with the following two changes:

- Change the `\titlestyle` command to the 'Roboto Slab' font
- Remove Georgia and subsequently the `\AtBeginEnvironment{}{}` command

Although I could've made those changes to the branch and merge the two commits, I would rather hear you thoughts first. So let me know. If these changes seem to make sense, feel free to add them to this pull request and I will merge it. I would be happy to add these additional changes myself if you want.

**Comment by rickstaa** [comment]
@dzwaneveld Your suggestions make sense. I forgot to remove the `Georgia` font. I created a new [c7933c3](https://github.com/dzwaneveld/TU-Delft-Unofficial-Report-Template/pull/5/commits/c7933c39263cc57379ae0282f88fd6bb85cf5267) to fix this. In this commit, I use `Roboto Slab Light` for `\titlestyle` instead of `Roboto Slab Regular` since Regular is, to my taste, a bit aggressive. However, feel free to change it to your liking.

**Comment by dzwaneveld** [comment]
Great suggestion. The regular does seem a bit aggressive, especially with boldface. Although that could be changed as well, `Roboto Slab Light` is indeed better suited. I have updated the comment to reflect these font changes and will merge. 

The documentation will be updated within at least 1-2 weeks. Given that Roboto is easily available for pdfLaTeX, I will make the appropriate changes there in the same timeframe. That change will entail a few more modifications I still wanted to make, but I have worked out most of them already. 

Thanks again for your input! If you have any other suggestions, I would be happy to know.

**Comment by rickstaa** [comment]
@dzwaneveld Thanks for merging my PR. I agree we could also use `Roboto Slab` while removing the `\bfseries` command from the titles. Feel free to use whatever version you seem fit! Looking forward to your changes.

**Pull request merged**
